import { Providers } from "@/Providers";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import React from "react";

export const metadata: Metadata = {
	title: "BetterThanDollar",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params: { locale },
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	const messages = await getMessages();
	// console.log("messages:", messages);

	return (
		<html lang={locale}>
			<body>
				<Providers>
					<NextIntlClientProvider
						messages={messages}
					>
						{children}
					</NextIntlClientProvider>
				</Providers>
			</body>
		</html>
	);
}
